/*
 * PINDEFINES.h
 *
 *  Created on: Jun 11, 2016
 *      Author: Vergil
 */

#ifndef INC_PINDEFINES_H_
#define INC_PINDEFINES_H_


#include "LPC17xx.h"
#include "lpc17xx_pinsel.h"

// LED1
#define LED1_PORT 	PINSEL_PORT_1
#define LED1_PIN	PINSEL_PIN_18
// LED2
#define LED2_PORT 	PINSEL_PORT_1
#define LED2_PIN	PINSEL_PIN_20
// LED3
#define LED3_PORT	PINSEL_PORT_1
#define LED3_PIN	PINSEL_PIN_21
// LED4
#define LED4_PORT	PINSEL_PORT_1
#define LED4_PIN	PINSEL_PIN_23


// UART3 (P9/Tx, P10/Rx)
#define UART3_TX_PORT	PINSEL_PORT_0
#define UART3_TX_PIN	PINSEL_PIN_0
#define UART3_RX_PORT	PINSEL_PORT_0
#define UART3_RX_PIN	PINSEL_PIN_1

// I2C
#define I2C2_SDA_PORT	PINSEL_PORT_0
#define I2C2_SDA_PIN	PINSEL_PIN_10
#define I2C2_SCL_PORT 	PINSEL_PORT_0
#define I2C2_SCL_PIN	PINSEL_PIN_11


// EXTI3 (Interrupts)
#define TOUCH_INT_PORT			PINSEL_PORT_0
#define TOUCH_INT_PIN			PINSEL_PIN_23
#define PUSHBUTTON_INT_PORT		PINSEL_PORT_0
#define PUSHBUTTON_INT_PIN		PINSEL_PIN_24

// SSP0 LCD Touch Controller
#define SSP0_CLK_PORT			PINSEL_PORT_0
#define SSP0_CLK_PIN			PINSEL_PIN_15
#define SSP0_MISO_PORT			PINSEL_PORT_0
#define SSP0_MISO_PIN			PINSEL_PIN_17
#define SSP0_MOSI_PORT			PINSEL_PORT_0
#define SSP0_MOSI_PIN			PINSEL_PIN_18

// Chip Select for SSP0
#define TOUCH_CS_PORT			PINSEL_PORT_0
#define TOUCH_CS_PIN			PINSEL_PIN_16

// SSP1 (SPI) LCD and SD card
#define SSP1_CLK_PORT			PINSEL_PORT_0
#define SSP1_CLK_PIN			PINSEL_PIN_7
#define SSP1_MISO_PORT			PINSEL_PORT_0
#define SSP1_MISO_PIN			PINSEL_PIN_8
#define SSP1_MOSI_PORT			PINSEL_PORT_0
#define SSP1_MOSI_PIN			PINSEL_PIN_9

// Chip Selects for SSPI1
#define SDMMC_CS_PORT			PINSEL_PORT_0
#define SDMMC_CS_PIN			PINSEL_PIN_6
#define LCD_CS_PORT				PINSEL_PORT_2
#define LCD_CS_PIN				PINSEL_PIN_5

// LCD Pins
#define LCD_RESET_PORT			PINSEL_PORT_2
#define LCD_RESET_PIN			PINSEL_PIN_4
#define LCD_DC_PORT				PINSEL_PORT_2
#define LCD_DC_PIN				PINSEL_PIN_3

#endif /* INC_PINDEFINES_H_ */
